FROM php:8.2-fpm-alpine

# Install PHP extensions
RUN apk add --no-cache zip libzip-dev unzip \
    && docker-php-ext-install pdo pdo_mysql zip

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
